### PR TITLE
Added Pace to storefront and other improvements

### PR DESCRIPTION
**Pull request by rav-redchamps**
Some improvements

- By default, the theme color was set to empty. So changed it to blue

### CODE REVIEW

**Review by SchumacherFM — APPROVED** [review]

**Comment by SchumacherFM** [comment]
Thank you very much @rav-redchamps

**Comment by rav-redchamps** [comment]
@SchumacherFM I have one more suggestion for you. What about submitting repository to https://packagist.org so that the composer installation process can be easier

**Comment by SchumacherFM** [comment]
@rav-redchamps Done! https://packagist.org/packages/schumacherfm/mage2-pace

**Comment by rav-redchamps** [comment]
Awesome! 

If you can update readme file as well to update composer installation instructions then that will be great.

From now on the below command should be enough to install the extension 

composer require schumacherfm/mage2-pace

Also, you might verify the issue https://github.com/SchumacherFM/Magento2-Pace/issues/3 with the latest version. This can be marked as resolved as well.

**Pull request merged**
